# Generated by Django 4.2.4 on 2023-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='src/media/products/default.png', upload_to='src/media/products/')),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('in_stock', models.IntegerField()),
                ('category', models.ManyToManyField(to='product.producttag')),
            ],
        ),
    ]
